config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "forecasts#index"

  # Resource route for forecasts
  resources :forecasts, only: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
# Represents a weather forecast at a particular time, for a particular location.
class Forecast
  include ActiveModel::Model

  def initialize(hourly_forecast_data)
    @hourly_forecast_data = hourly_forecast_data
  end

  def current_temperature
    degrees = @hourly_forecast_data.dig('properties', 'periods', 0, 'temperature')
    unit = @hourly_forecast_data.dig('properties', 'periods', 0, 'temperatureUnit')

    return "unknown" unless degrees
    "#{degrees}° #{unit}"
  end

  def short_forecast
    @hourly_forecast_data.dig('properties', 'periods', 0, 'shortForecast')
  end

  def from_cache?
    @hourly_forecast_data.dig('from_cache')
  end
end

app/models/location.rb
class Location
  include ActiveModel::Model

  attr_accessor :display_name, :lat, :lon, :postal_code

  # Search for a Location, using an external geocoding service.
  # Returns nil if the search did not find a location
  def self.search(address_search)
    result = Geocoder.search(address_search).first
    return nil unless result

    Location.new({
      display_name: result.display_name,
      lat: result.latitude,
      lon: result.longitude,
      postal_code: result.postal_code.to_s,
    })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def index
    @address_search = params[:address_search]

    if @address_search
      @location = Location.search(@address_search)
      @forecast = ForecastLookup.by_location(@location)
    end
  rescue ForecastLookup::APIError => e
    @api_error = true
    puts e.inspect
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_search_form.erb
<form action="<%= forecasts_path %>" method="GET">
  <label for="address_search">Enter an address:</label>
  <input type="text" name="address_search" value="<%= @address_search %>">
  <input type="submit" value="Submit">
</form>

app/views/forecasts/index.html.erb
<h1>Forecasts</h1>

<%= render 'search_form' %>

<% if @address_search && @location.nil? %>
  <p>No location found.</p>
<% end %>

<% if @location %>
  <h2>Forecast for <%= @location.display_name %></h2>
<% end %>

<% if @api_error %>
  <p>There was a problem retrieving the forecast from the weather API.  This happens occasionally (hey, it's free).  Try again?</p>
<% end %>

<% if @forecast %>
  <h3>Current Temperature: <%= @forecast.current_temperature %></h3>
  <p><%= @forecast.short_forecast %></p>

  <%=  @forecast.from_cache? ? "Cached forecast" : "New forecast (not cached)" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>